### PR TITLE
Add first/last aggregation types.

### PR DESCRIPTION
**Pull request by karanlyons**
These aggregations are very useful for timeseries data like kline/candlestick charts.

### CODE REVIEW

**Comment by danni-m** [comment]
@karanlyons Looks good, can you please add a test that the downsampling happens as it should in `tests/test_module.py`?

**Comment by karanlyons** [comment]
Sure! I don’t immediately see examples of tests for the other aggregation types, shall I add tests for all of them?

**Comment by danni-m** [comment]
@karanlyons you are right.
Let me test this code before I push it. if you can create a UT that will be great as well.

**Comment by karanlyons** [comment]
I pushed tests to my branch. Weirdly they all pass _except_ for `avg`, which fails as redis(-py) returns longs for the timestamps. It’s not immediately clear to me why the rest would not have this issue.

**Comment by danni-m** [comment]
@karanlyons Awesome, i'll into it tomorrow. thanks!

**Pull request merged**
